### ISSUE TITLE
output folders

### ISSUE THREAD

**Issue by koenvandenberge** [pinellolab/scATAC-benchmarking#4]
Hi,

Thank you for creating this evaluation framework and accompanying repository.
The README mentions output folders for all real datasets, but these are not present.
Is it possible to add these, or, like with the input folder, a link to a Dropbox folder?

Thanks,
Koen

**Comment by huidongchen** [comment]
Hi Koen,

Thanks for your interest in our benchmark work. Currently we only keep the `output` to illustrate the benchmarking work structure. Due to the file size limit by Github, we didn't upload the result files. But using a Dropbox link is a good idea. I will try to clean up the files a bit and upload them in the next few days.

**Comment by drbecavin** [comment]
Hello,
Thank you also for your amazing assessment of scATAC-Seq techniques !
It will really help a lot the community.
I am trying your notebooks, and they are well done.
Regarding the files on dropbox, maybe you could provide the method to create them from raw data. I am talking more specifically about the 10x_PBMC_5k.tar.gz. How did you do the thousand "dedup" files ?
Maybe I miss it, but you should provide the sh file to create them, it would help. Otherwise we rely on your dropbox files, which is not ideal.

Thanks

**Comment by huidongchen** [comment]
The output files have been uploaded (The `output` link is enabled now). 

@drbecavin I have uploaded the python script that's used to split single bam file from 10x.  "https://github.com/pinellolab/scATAC-benchmarking/blob/master/Real_Data/10x_PBMC_5k/input/sc-bams_nodup/split_bam_file.py"
