### ISSUE TITLE
Cannot implement function 'runJaccard()' in SnapATAC

### ISSUE THREAD

**Issue by Van1yu3** [pinellolab/scATAC-benchmarking#5]
When I tried to reproduce the results using the code for the method SnapATAC, the code returned some errors. More specifically, the error occurred when the function `runJaccard()` was implemented in this [Jupyter Notebook](https://nbviewer.jupyter.org/github/pinellolab/scATAC-benchmarking/blob/master/Real_Data/Buenrostro_2018/run_methods/SnapATAC/SnapATAC_buenrostro2018.ipynb) file. Actually, according to the help page in the R package SnapATAC, the function `runJaccard()` only permits 6 argument inputs, while in the Jupyter Notebook the number of arguments is 9. 

Furthermore, when I removed the unused arguments in `runJaccard()`, I got another error:

> Error in (function (cl, name, valueClass)  :
>   ‘method’ is not a slot in class “jaccard”
> Calls: runJaccard -> runJaccard.default -> <Anonymous>
> Execution halted

Thank you for your help if you could fix this bug!

**Comment by huidongchen** [comment]
It looks like SnapATAC author has updated several functions. Unfortunately he did not keep records of different release versions. That's why even if you are using the same version, some functions are actually different already. So I guess it will be difficult to address this on my end. 

If you simply want to validate the results shown in our paper, I can share with you the saved R image file. If you want to use SnapATAC tool, I think it would make more sense if you check out their github page and follow their latest tutorials.

**Comment by Van1yu3** [comment]
Thank you for your reply! Then I think I need to go to the SnapATAC GitHub page.
