### ISSUE TITLE
Additional information to run the metrics for 10xpbmc5k

### ISSUE THREAD

**Issue by DaneseAnna** [pinellolab/scATAC-benchmarking#6]
Hi, 

I am trying to reproduce your benchmarking to compare [epiScanpy](https://www.biorxiv.org/content/10.1101/648097v1) performance to the other methods you already tested.
So far it has been working very well, however I am missing one file to compare the gene score metric in the 10pbmc5k dataset. In your notebook it is signal as: ./run_methods/GeneScoring/FM_GeneScoring_10xpbmc5k.tsv
 Maybe it is somewhere obivous, but I haven't found it. Would it be possible to make this file accessible? 

Best, 
Anna

**Comment by huidongchen** [comment]
Hi Anna,

You are right. Since the file is relatively big, it was blocked when I tried to upload the output files. 

But anyway i have added a download link for it. It can be found at https://github.com/pinellolab/scATAC-benchmarking/tree/master/Real_Data/10x_PBMC_5k/run_methods/GeneScoring

Thanks for the feedback.
