### ISSUE TITLE
docker ?

### ISSUE THREAD

**Issue by DaneseAnna** [pinellolab/scATAC-benchmarking#7]
Hi, 
I am interested in reproducing your benchmarking but there is a lot of methods to implement. Do you have a docker environment with the different methods implemented by any chance?

Best, 
Anna

**Comment by huidongchen** [comment]
Unfortunately we don't really have a docker image and I don't think it's feasible to install all pkgs in the same env since there are many conflicts between the dependencies.  We had to create a separate env for each of the methods we assessed. 

But I assume as long as you use the packages of the same version as shown in our notebooks, the results should be mostly reproducible.
